### ISSUE TITLE
Improvements to Orca API specification

### ISSUE THREAD

**Issue by sharpie7** [orcajs/orca.js#13]
Having worked on the Orca demo I would like to make some proposals for improving the Orca API specification. These are mostly in the spirit of improvements that will simplify interoperability while not expanding the scope of the API.

## Specification of "optional" procedures/methods
De-facto a number of methods in the API are optional - eg call.sendDTMF. I suggest we identify the non-core methods and document them as being optional. Application implementors can test for whether optional methods are implemented eg by testing "(typeof call.sendDTMF=== "function")".

This approach does not provide a general solution for optionality/extensibility as, for example, it doesn't deal with how to add new event types to exising objects. However it would clarify at least one area where different API approaches can exist.

## Error handling when number of calls or sessions limit is reached.
It would be helpful to define how errors where the number of calls or sessions allowed has been reached are handled. One approach could be to create a "doomed" object which immediately throws an error event. 

## Indication of media type for incoming calls
This is an old proposal but should be implemented.

## Simplification of ".off" methods
The stub and the reflector allow call.off() and session.off() to be called without parameters to remove all event listeners. I think this should be a documented part of the API.

**Comment by aecostas** [comment]
The first point is close related to https://github.com/orcajs/orca.js/issues/11 (Core API vs Extension). The range of applications on top of sippojs might be very wide: from simple click2call applications to make one-to-one calls to complex collaboration services, including some fancy datachannels-based functionalities like cobrowsing. So, having a complete and powerful transport library that supports all the available features might not be needed in some scenarios. How do we handle this?
I envision two approaches:
    - provide a complete library and use only a subset of features. The main drawback of this is that very simple applications, like the click2call, will include a big and heavy library. In addition, it will expose in the browser some client side code, which may not be desired in some cases.
    - encapsulate orcajs features in extensions and choose which extension(s) to include at compilation time. It is like other javascript frameworks, like jQuery, work. Extension will use the functionalities provided by the CORE API (example: the user should have an active session(Core API) to use a functionality provided by an extension).

Regarding the optional methods, I think they are compatible with extensions (for instance, the Core API or the extension that manages the Call can provide the DTMF or not). But, how does the API should expose this?
- 1) object introspection, that is, by inspecting if a method exist or not (typeof, as suggested by @sharpie7)
- 2) implement the optional function, but returning immediately with an error code to indicate that this feature is unimplemented
- 3) provide a "capabilities" method (already mentioned in https://github.com/orcajs/orca.js/issues/8 by @skapauan ).

I lean more towards a combination of 2+3. By using the capabilities method, the application is able to adapt its user interface depending on the available functionalities (for instance not showing a button for putting a call on hold if the transport layer does not support this feature). This could also be achieved by object introspection but, in my humble opinion, it has some drawbacks:
- if the API changes in the future it would imply more changes in the application code (this is just a minor issue)
- a capability can encapsulate several functionalities, so the number of checks would decreases (example: from the capability "call", the application could infer that there is a call and a hangup method)
- handling events. We only have the .on method so there is no way to know in advance, using introspection, which are the possible events to be triggered by the transport layer.

With this approach 2) will be also needed for robustness of the API.

In other hand... if, in the end, extensions are used, there will be a new question to think about: should the extensions provide only new functionalities or would be they also intended for modifying/overwriting the functionality of the CORE API or another extension?

**Comment by sharpie7** [comment]
Thanks @aecostas . I think this discussion should continue on issue number #11 as that was originally intended to be the general discussion on extensibility. This issue was ment to deal with specific changes of very limited scope which have now been incorporated in the API. I will mark this issue as closed and add your text to issue #11.
