### ISSUE TITLE
Need a way to determine media types of an incoming call

### ISSUE THREAD

**Issue by skapauan** [orcajs/orca.js#5]
An outgoing call is set up like this:

```
session.createCall('3335557777', 'audio,video');
```
Presumably the 'audio,video' is used to inform the other party of which media types they are being invited to share. But when the other party receives notification of the incoming call, there is no Call method to access this information, and there is no incoming media stream yet to see what the other party is already sharing.

I suggest adding a method such as __Call.mediaTypes()__, that would return a string of media types in the call.
* In an incoming or outgoing call before the recipient answers, return the media types which the call initiator invited the recipient to share.
* In a connected call, return the current media types of the call. (It is tough to say what to return if the streams from each side do not match, such as one-way video. Perhaps if a media type is present at all, it would appear in the returned value.)
* In an ended or failed call, return an empty string.

**Comment by sharpie7** [comment]
I have accepted a pull request to add a media type to incoming calls in the API. On that basis I am closing this issue.
